select FIRST_HALF.FLAVOR
from FIRST_HALF, ICECREAM_INFO
where FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
and FIRST_HALF.TOTAL_ORDER > 3000
and ICECREAM_INFO.INGREDIENT_TYPE like 'fruit_based'
order by FIRST_HALF.TOTAL_ORDER desc;